repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8

  - repo: https://github.com/prettier/prettier
    rev: 1.16.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.6.0 # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@5.6.0
          - babel-eslint@9.0.0
          - eslint-config-airbnb@17.1.0
          - eslint-plugin-import@2.17.2
          - eslint-plugin-jsx-a11y@6.2.1
          - eslint-plugin-react@7.13.0
          - eslint-plugin-prettier@3.1.0
          - eslint-config-prettier@4.3.0
