# .travis.yml
language: python 
    python: 
      - "3.6"
      - "3.7"
    env: 
      -DJANGO=1.8 DB=mysql
    install: 
      - pip install -r requirements.txt
    script: 
      - python manage.py test
# vim:ft=ansible
